language: node_js
node_js:
  - "7"
  
sudo: required
services:
  - docker

 before_install:
  - docker build -t ddbogdanovich/docker-react -f Dockerfile.dev .

  sctipt:
   - docker run ddbogdanovich/docker-react npm run test -- --coverage 